accounts/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from .import views

app_name='accounts'

urlpatterns=[
url(r'^signup/$', views.signup_view, name="signup"),
url(r'^login/$',views.login_view,name="login"),
url(r'^logout/$',views.logout_view,name="logout")
]

campaign/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from .import views

app_name='campaign'

urlpatterns=[
url(r'^$',views.campaign,name="create"),
url(r'^review/',views.review,name="review"),
url(r'^delete/',views.delcontacts,name="delcontacts"),
url(r'^send/',views.send,name="send"),
url(r'^restart/',views.restart,name="restart"),
url(r'^upcsv/',views.upcsv,name="upcsv"),
url(r'^upload/csv/$', views.upload_csv, name='upload_csv'),



]

mail_bot/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from .import views

app_name='home'


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.home,name="home"),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^campaign/',include('campaign.urls')),

]

accounts/models.py
from django.db import models

# Create your models here.

campaign/models.py
from django.db import models


# Create your models here.
class Contacts(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)

    def __str__(self):
        return self.email

campaign/forms.py
from django import forms
from . import models


class CreateContacts(forms.ModelForm):
    class Meta:
        model = models.Contacts
        fields = ['name','email']

accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout

def signup_view(request):
    if request.method == 'POST':
         form = UserCreationForm(request.POST)
         if form.is_valid():
             user = form.save()
             #  log the user in
             login(request,user)
             return redirect('home')
    else:
        form = UserCreationForm()

    return render(request, 'accounts/signup.html', { 'form': form })


def login_view(request):
    if request.method == 'POST':
         form = AuthenticationForm(data=request.POST)
         if form.is_valid():
             #  log the user in
             user = form.get_user()
             login(request,user)
             if 'next' in request.POST:
                 return redirect(request.POST.get('next'))
             else:
                 return redirect('home')
    else:
        form = AuthenticationForm()

    return render(request, 'accounts/login.html', { 'form': form })


def logout_view(request):
    if request.method=='POST':
        logout(request)
        return redirect('home')

campaign/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render,redirect,reverse
from .models import Contacts
from django.contrib.auth.decorators import login_required
from . import forms
import logging
from django.contrib import messages
import smtplib
import time
app_name='campaign'


@login_required(login_url="/accounts/login/")
def campaign(request):
    if request.method=='POST':
        form=forms.CreateContacts(request.POST,request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()            #save it
            return redirect('campaign:send')

    else:
        form = forms.CreateContacts()
    return render(request,'campaign/campaign.html',{'form':form})



# def send(request):
#     return HttpResponse('sent')


def upcsv(request):
    return redirect('campaign:upload_csv')

def upload_csv(request):
    data={}
    if "GET" == request.method:
        return render(request,"campaign/upload_csv.html",data)
    else:
        csv_file=request.FILES["csv_file"]
        file_data=csv_file.read().decode("utf-8")
        lines=file_data.split("\n")
        for line in lines:
            fields=line.split(",")
            print("sdfcsd"+fields[0])
            print("sdcdv"+fields[1])
            data_dict = dict()
            data_dict["name"]=fields[0]
            data_dict["email"]=fields[1]
            form=forms.CreateContacts(data_dict)
            if form.is_valid():
                form.save()
            else:
                print("error")
    return HttpResponseRedirect(reverse("campaign:review"))

def review(request):
    contacts=Contacts.objects.all()
    return render(request,"campaign/review.html",{'contacts':contacts })


def delcontacts(request):
    print("hello")
    Contacts.objects.all().delete()
    print("deleted")
    return HttpResponseRedirect(reverse("campaign:upload_csv"))

def send(request):
    server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
    server.login("man11invisible", "*")

    contacts=Contacts.objects.all()

    for contact in contacts:
        name=contact.name
        email=contact.email
        server.sendmail(
          "30hrs1999@gmail.com",
          email,
          "Hello! "+name+" keep up with you good work.")
        print(str(email),"\n")
        time.sleep(60)
    server.quit()

    return render(request,"campaign/successful.html")


def restart(request):
    return HttpResponseRedirect(reverse("campaign:create"))

mail_bot/views.py
from django.http import HttpResponse
from django.shortcuts import render

app_name='main'

def home(request):
    return render(request,'base_layout.html')
    #return HttpResponse('Hello')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="container">

    <h1 style="color:#FFD700;">Login</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
        <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif %}
        <input class="ml-auto mr-auto" type="submit" style="text-align:center;" value="Login">
    </form>
  </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="container">
    <h1 style="color:#FFD700;">Signup</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input class="ml-auto mr-auto" type="submit" value="Signup">
    </form>
  </div>
{% endblock %}

campaign/templates/campaign/campaign.html
{% extends 'base_layout.html' %}
{% block content %}
  <div class="create-campaign" id="overlay">
    <h2>Add Contacts Manually</h2>
    <form class="site-form" action="{% url 'campaign:create'%}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{form}}
      <input class="ml-auto mr-auto" type="submit" value="Create">
    </form>
    <h3 style="text-align:center">OR Upload CSV</h3>
<form class="site-form" action="{% url 'campaign:upcsv' %}" method="get">
  <input class="ml-auto mr-auto" type="submit" value="Upload CSV">
  <!-- <button type="sumbmit" name="button">Upload CSV</button> -->
</form>
{% endblock %}

campaign/templates/campaign/review.html
{% extends 'base_layout.html' %}
{% block content %}
  <div class="container review">

    <form class="site-form" action="{% url 'campaign:delcontacts' %}" method="get">
    <button type="submit" name="button">Delete Contacts</button>
    </form>
    <form class="site-form" action="{% url 'campaign:upcsv' %}" method="get">
      <button type="submit" name="button">Append More CSV Entries</button>
    </form>
    <form class="site-form" action="{% url 'campaign:send' %}" method="get">
      <button type="submit" name="button">Send</button>
    </form>
<hr>
</div>
<div class="container">
  <table id="example" class="display" style="width:100%">
          <thead>
              <tr>
                  <th>Name</th>
                  <th>Email</th>
              </tr>
          </thead>
          <tbody>
            {% for contact in contacts %}
              <tr>
                  <td>{{contact.name}}</td>
                  <td>{{contact.email}}</td>
              </tr>
            {% endfor %}
          </tbody>


  </div>

{% endblock %}

campaign/templates/campaign/successful.html
{% extends 'base_layout.html' %}
{% block content %}
<div class="successful">
  <h3>Action Successfull</h3>
  <p>wanna start more campaigns?</p>
  <form class="site-form" action="{% url 'campaign:restart' %}" method="get">
    <button type="submit" name="button">New campaign</button>
  </form>

</div>
{% endblock %}

campaign/templates/campaign/upload_csv.html
{% extends 'base_layout.html' %}
{% block content %}
<div class="container">

<form action="{% url "campaign:upload_csv" %}" method="POST" enctype="multipart/form-data" class="form-horizontal">
{% csrf_token %}
<div class="form-group">
    <label for="name" class="col-md-3 col-sm-3 col-xs-12 control-label">File: </label>
    <div class="col-md-8">
        <input type="file" name="csv_file" id="csv_file" required="True" class="form-control">
    </div>
</div>
<div class="form-group">
    <div class="col-md-3 col-sm-3 col-xs-12 col-md-offset-3" style="margin-bottom:10px;">
         <button class="btn btn-primary"> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"></span>Upload </button>
    </div>
</div>
</form>
</div>

{% endblock %}

templates/base_layout.html
{% load static from staticfiles  %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Mail-Bot</title>
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="{% static 'style.css' %}" rel="stylesheet" >
  <link href="{% static 'datatables/datatables.min.css' %}" rel="stylesheet" >
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet' %}" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <!-- <link href="{% static 'vendor/css/clean-blog.min.css' %}" rel="stylesheet"> -->
  </head>
  <body style="background-color:black;">
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container-fluid" style="background-color:#FFD700;margin-bottom:10px;">
        <a class="navbar-brand" href="{% url 'home' %}">Mail-Bot</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="campaign/">Campaign</a>
            </li>
            <li>
              <a class="nav-link" href="{% url 'home' %}">Home</a>

            </li>


            {% if user.is_authenticated %}
            <li class="nav-item">
              <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                {% csrf_token%}
                <button class="logout btn-primary" style="margin-top:5px;" type="submit">Logout</button>
              </form>
            </li>

            {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a></li>
            {% endif %}
          </ul>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <h1 style="margin-top:100px;z-index:1;color:#FFD700;">I'M MAIL-BOT</h1>
      <!-- <button class="btn btn-primary" style="text-align:center;position:fixed;top:50%;left:45%;"> -->
        <!-- <a href="/campaign">New Campaign</a> -->
      <!-- </button> -->

    </div>
    {% block content %}
    {% endblock %}
    <!-- Footer -->
    <!-- <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; Your Website 2018</p>
          </div>
        </div>
      </div>
    </footer> -->


   <!-- cryptaris -->
   <script src='http://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.5.0/lodash.min.js'></script>
   <script src='http://cdnjs.cloudflare.com/ajax/libs/three.js/r70/three.min.js'></script>
   <script  src="{% static 'js/index.js' %}"></script>

   <script src="{% static 'datatables/jquery-3.3.1.min.js' %}"></script>

   <script src="{% static 'datatables/datatables.min.js' %}">

   </script>
    <!-- <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script> -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
   <script type="text/javascript">
   $(document).ready(function() {
    $('#example').DataTable();
} );

   </script>
    <!-- Custom scripts for this template -->
    <!-- <script src="{% static 'vendor/js/clean-blog.min.js' %}"></script> -->

    </body>
    </html>